version: '3.7'

services:
  mongen-core:
    container_name: mongen_core_dev
    build:
      context: ${HOME}/mongen/mongen-core
      dockerfile: ${HOME}/mongen/mongen-core/dev/Dockerfile
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=postgres://mongen:123123@db:5432/mongen_db
    networks:
      - mongen-network
    volumes:
      - ${HOME}/mongen/mongen-core:/app
    links:
      - db
    depends_on:
      - db


  mongen-frontend:
    container_name: mongen_frontend_dev
    build:
      context: ${HOME}/mongen/mongen-frontend
      dockerfile: Dockerfile
    volumes:
      - '${HOME}/mongen/mongen-frontend:/app'
    ports:
      - '3000:3000'
      - '9229:9229'
    environment:
      - NODE_ENV=development
      - MONGEN_CORE_URL=http://localhost:8080
      - MONGEN_CORE_INTERNAL_URL=http://mongen-core:8080
      - MONGEN_MEDIA_URL=http://localhost:9090
    networks:
      - mongen-network
    links:
      - mongen-core
      - mongen-media

  db:
    image: "postgres:12"
    container_name: mongen_db_dev
    environment:
      - POSTGRES_USER=mongen
      - POSTGRES_PASSWORD=123123
      - POSTGRES_DB=mongen_db
    networks:
      - mongen-network
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./core_db_scripts:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mongen -d mongen_db"]
      interval: 10s
      timeout: 5s
      retries: 5


  mongen-media:
    container_name: mongen_media_dev
    build:
      context: ${HOME}/mongen/mongen-media
      dockerfile: Dockerfile
    environment:
      - APP_SETTINGS=config.DevelopmentConfig
      - DATABASE_URL=postgresql://mongen:123123@media-db/mongen_media_db
    volumes:
      - '${HOME}/mongen/mongen-media:/app'
    networks:
      - mongen-network
    ports:
      - '9090:9090'
    restart: on-failure
    links:
      - media-db
    depends_on:
      - media-db

  media-db:
    image: "postgres:12"
    container_name: mongen_media_db_dev
    environment:
      - POSTGRES_USER=mongen
      - POSTGRES_PASSWORD=123123
      - POSTGRES_DB=mongen_media_db
    networks:
      - mongen-network
    ports:
      - '5433:5432'
    volumes:
      - ./postgres-data-media:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mongen -d mongen_media_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: "jboss/keycloak"
    container_name: mongen_keycloak_dev
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      # - DB_VENDOR=postgres
      # - DB_ADDR=postgres://mongen:123123@db:5432/mongen_db
      # - DB_DATABASE=mongen_db
      # - DB_USER=mongen
      # - DB_PASSWORD=123123
    networks:
      - mongen-network
    ports:
      - '8095:8080'

networks:
  mongen-network:
